wandb_version: 1

seed:
  desc: null
  value: 1
environment:
  desc: null
  value:
    render: true
    eval_every_n: 500
    update_every_n: 20
    num_threads: 32
    simulation_dt: '0.0025'
    control_dt: '0.01'
    max_time: '4.0'
    root_guided: true
    visualize: false
    unseen: true
    new_category: false
    load_set: mixed_train
    hand_model_r: ur5_leap.urdf
    finger_action_std: '0.015'
    rot_action_std: '0.01'
    reward:
      affordance_reward:
        coeff: '0.5'
      affordance_contact_reward:
        coeff: '1.5'
      affordance_impulse_reward:
        coeff: '0.5'
      table_reward:
        coeff: '-0.01'
      table_contact_reward:
        coeff: '-1.0'
      table_impulse_reward:
        coeff: '-0.5'
      arm_height_reward:
        coeff: '-0.02'
      arm_contact_reward:
        coeff: '-0.1'
      arm_impulse_reward:
        coeff: '-0.1'
      direction_reward:
        coeff: '-0.1'
      center_reward:
        coeff: '-1.0'
      obj_displacement_reward:
        coeff: '-1.0'
      wrist_vel_reward_:
        coeff: '-0.001'
      wrist_qvel_reward_:
        coeff: '-0.0001'
      obj_vel_reward_:
        coeff: '-1.5'
      obj_qvel_reward_:
        coeff: '-0.01'
      anatomy_reward:
        coeff: '-0.0'
      torque:
        coeff: '-0.0'
architecture:
  desc: null
  value:
    policy_net:
    - 128
    - 128
    value_net:
    - 128
    - 128
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731337759
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.17.2
      8:
      - 5
      13: linux-x86_64
