executable = cluster.sh
arguments = $(Process)
error = condor_logs/$(Cluster).$(Process).err
output = condor_logs/$(Cluster).$(Process).out
log = condor_logs/$(Cluster).$(Process).log
request_memory = 32000
request_cpus=48
request_gpus=1
requirements=CUDADeviceName=="Tesla V100-PCIE-16GB" || CUDADeviceName=="Tesla V100-PCIE-32GB" || CUDADeviceName=="Tesla V100-SXM2-32GB" || CUDADeviceName=="GeForce RTX 2080 Ti"
queue 10
