# general config.yaml

mode: train # or eval (quantitative)
eval_name: null 
exp:
  logdir: null
  log_name: null
  seed: 1
  num_iterations: 4001
  load_trained_policy: false

exp_name: null # Train mode: User defined experiment name
weight: /home/hang/raisim/SafeGrasp/raisimGymTorch/data_all/add_object_properties/OBJMASS025/full_3500_r.pt
task_name: null # the experiment environment, in /envs/${task_name}
task_path: null 
single_obj: False
load_param_path: null # load pretrainded model path 

data:
  storedir: data_all

env_settings:
  mass: null # kg


random_prior:
  use: False
  mass_bound: [0.1, 0.6] # kg
  mu_bound: [0.8, 0.8] #  friction coefficient

use_QP_reward: True

# defaults:
#   - env: allegro_teacher/cfgs/cfg_reg  

# python raisimGymTorch/general/run.py mode=train task_name=allegro_teacher_new_reward exp.log_name=single_obj_new_reward exp.num_iterations=10000 random_prior.use=False exp_name=allegro_teacher_new_reward


