# general config.yaml

mode: train # or eval (quantitative)

exp:
  logdir: null
  log_name: null
  seed: 1
  num_iterations: 4001
  load_trained_policy: false

exp_name: null # Train mode: User defined experiment name
weight: /home/hang/raisim/RobustDexGrasp/raisimGymTorch/data_all/add_object_properties/OBJMASS025/full_3500_r.pt
task_name: null # the experiment environment, in /envs/${task_name}
task_path: null 

load_param_path: null # load pretrainded model path 

data:
  storedir: data_all

random_prior:
  use: True
  mass_bound: [0.02, 0.6] # kg
  mu_bound: [0.1, 1.2] #  friciton coefficient


# defaults:
#   - env: allegro_teacher/cfgs/cfg_reg  