# general config.yaml

mode: train # or eval (quantitative)

exp:
  logdir: null
  log_name: null
  seed: 1
  num_iterations: 4001
  load_trained_policy: false

exp_name: null # Train mode: User defined experiment name
weight: /home/hang/raisim/RobustDexGrasp/raisimGymTorch/data_all/add_object_properties/OBJMASS025/full_3500_r.pt
task_name: null # the experiment environment, in /envs/${task_name}
task_path: null 

load_param_path: null # load pretrainded model path 

data:
  storedir: data_all

random_prior:
  use: True
  mass_bound: [0.05, 0.5] # kg
  mu_bound: [0.4, 0.8] #  friction coefficient


# defaults:
#   - env: allegro_teacher/cfgs/cfg_reg  

# python raisimGymTorch/general/run.py mode=train task_name=QP_as_input_reward exp.log_name=QP_as_reference exp.num_iterations=10000 random_prior.use=False exp_name=allegro_teacher_new_reward